### ISSUE TITLE
Shortlink for Tag Archive Permalink

### ISSUE THREAD

**Issue by SarahHaruel** [willnorris/wordpress-hum#21]
Great plugin !
Can this work for tag archive's where the shorter is strictly tied to the tag archive permalink ?
Can this be linked to the firebase console ?

**Comment by pfefferle** [comment]
It should be technically possible, but this plugin follows the "Whistle" spec: http://tantek.pbworks.com/w/page/21743973/Whistle#design and there seem to be no "prefix" for archive pages.

/cc @willnorris any ideas about that?

**Comment by pfefferle** [comment]
@tantek any ideas?

**Comment by dshanske** [comment]
You could use i. It is technically defined as an identifier on another system using subdirectory as system id space. But you could use it as a local identifier. So, /i/t/ in theory
Otherwise, Whistle isn't a spec per say. Several people deviated from it. There are several unused letters you could designate as archive shortcodes. However, the issue is that WordPress has tags, categories, other taxonomies, date archives...

**Comment by SarahHaruel** [comment]
Would it be major heart surgery to tweak to make it work or its something hat is realistically possible ( happy to donate / but a beer )

**Comment by pfefferle** [comment]
@dshanske I tended to use `m` instead:

> m - (message like email, permalink to external list archive, or private blog archive, or a sender-hosted message)

**Comment by SarahHaruel** [comment]
Does this mean it’s possible ?

**Comment by pfefferle** [comment]
In gerneral: yes. But I am still thinking loud.

**Comment by SarahHaruel** [comment]
> In gerneral: yes. But I am still thinking loud.

My last throw of the dice - is this possible or should I give up hope ?

**Comment by SarahHaruel** [comment]
;0)

**Comment by willnorris** [comment]
Since all taxonomies (tags, categories, custom) are in the same table, a single prefix could handle them all.  As @dshanske noted, Whistle certainly isn't a spec, and all of us who have built custom shorteners have just used it as a guide.  I don't have a problem deviating from Whistle for this type.

Though this does perhaps argue for making it easier for people to override the default prefixes that hum uses.  Right now they are hardcoded.  That way if whatever we select for taxonomies conflicts with something a user was already using, they can pretty easily change that.
