### ISSUE TITLE
shortcode please!!!!!!!

### ISSUE THREAD

**Issue by smartcontentor** [willnorris/wordpress-hum#27]
hello
please add shortcode for this plugin 
thank you

**Comment by willnorris** [comment]
can you say a little bit more about how you would use this?  

For example, do you just need the plain text of the shortlink URL, or would you also want it to be an HTML link?  If a link, would the text of the link just be the URL itself, or would you want that to be overridable?

Presumably, you might be wanting to add this to every post, in which case would it be better to add it to your theme, rather than a shortcode in each individual post?

**Comment by pfefferle** [comment]
@smartcontentor can you give a bit more context please?
