### ISSUE TITLE
Feature Request: eliminate /*/

### ISSUE THREAD

**Issue by starlyth** [willnorris/wordpress-hum#31]
I use a secondary url for the shortening. I would like the ability to not have /b/ in the links. I understand why (post types and structural reasons) this is not always advised. This just adds (for me) 2 extra characters I don't need.

**Comment by willnorris** [comment]
Off the top of my head, I can't easily imagine a way to support this natively without it being pretty disruptive to the existing code and risking side-effects.  However, if you don't mind writing some minimal code, it should be doable with the existing filters (any maybe one or two new ones if necessary).

If you're okay with your "canonical" shortlinks still being of the form `/b/123` (meaning that's still what's advertised in your `<link rel=shortlink>`, and you just want to also be able to resolve `/123` links, you can use the `hum_legacy_id` filter.  Just use a variation of the [legacy_ftl_id() function](https://github.com/willnorris/wordpress-hum/blob/f695cb5dc0ee827b29c554580a0fe2db44cb9a25/hum.php#L407-L420).  I haven't tested this, but conceptually something like:

```php
add_filter('hum_legacy_id', function($id, $path) {
  return sxg_to_num($path);
}, 10, 2);
```

If you actually want the `/123` URL advertised in your `<link rel=shortlink>`, then you'd likely need to replace the [get_shortlink() function](https://github.com/willnorris/wordpress-hum/blob/f695cb5dc0ee827b29c554580a0fe2db44cb9a25/hum.php#L296-L316) to do what you want.  

Ideally, you'd be able to use the `hum_type_prefix` filter to always return an empty prefix:

```php
add_filter('hum_type_prefix', '__return_empty_string');
```

But then you'd have an advertised shortlink with a double slash: `//123`.  We could pretty easily add a check to prevent that.  Alternately (and I kind of prefer) adding a new filter at the end of the existing get_shortlink function along the lines of:

```php
return apply_filters('hum_get_shortlink', $link, $base, $post_id, $type);
```

That would allow any manner of customization, and for your use case, you could do something like:

```php
add_filter('hum_get_shortlink', function($link, $base, $id, $type) {
  if ($id) {
    $link = trailingslashit( $this->shortlink_base() ) . num_to_sxg($id);
  }
  return $link;
}, 10, 4);
```

@pfefferle what do you think?

**Comment by willnorris** [comment]
Actually... given the recent change in 25d9bebdc006f5a29a23175be9b5aea7df2f8a09, I wonder if emptying out the local_types array would end up doing the right thing?  So basically just calling:

```php
add_filter('hum_local_types', '__return_empty_array');
```

Looking at the regex used in [rewrite_rules](https://github.com/willnorris/wordpress-hum/blob/f695cb5dc0ee827b29c554580a0fe2db44cb9a25/hum.php#L243-L248), I actually think that might work, though it is much more likely to cause side-effects with other rewrite rules from WordPress core or other plugins.  It's much safer to use the `hum_legacy_id` filter, since that hooks into the WordPress 404 handler, after all other rewrite rules have run.

**Comment by willnorris** [comment]
Err scratch that last comment... since I think we are always including `i` as a local type (not sure why?) when setting up the rewrite rule, that wouldn't work.  Even if that weren't the case, we're still looking for an additional forward slash, so it wouldn't match.  It was probably a bad idea anyway :)

```php
add_rewrite_rule( "([{$local_types}i](\/.*)?$)", 'index.php?hum=$matches[1]', 'top' );
```

**Comment by starlyth** [comment]
Thanks, Will!

I just discovered the plugin, so the impact wouldn't be too great for me if I coded things in. I can see how removing the base could cause a URL collision between 2 bases that were removed. From what I understand, the likelihood is small, but it would exist, so perhaps my request is not so good.

**Comment by starlyth** [comment]
Looking at the [proposed "standard" of shortlinks](http://microformats.org/wiki/rel-shortlink), it appears that the /*/ is part of the proposal. With that being the case, my idea wouldn't be good. I understand that it really is a proposal, but as that seems to be an integral part, I'll move on from my crazy idea. I like to future proof as much as possible.
